Leo p
FrancoisBontemps/Interview_viseo pull request #1
Opened 2019-03-18 17:10 UTC by leopalazzi

PR #1

2019-03-18 18:23 UTC, therveux requested changes

2019-03-18 18:23 UTC, therveux commented on .idea/vcs.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Mettre le dossier .idea/ dans le fichier .gitignore

2019-03-18 18:23 UTC, therveux commented on react_project/src/App.js
>  class App extends React.Component {
Utilise la variable destructurée plus haut 
``` js
class App extends Component 
```

2019-03-18 18:23 UTC, therveux commented on react_project/src/App.js
> +    constructor(props) {
Pas besoin de passer par le constructor pour initialiser votre state.
Vous pouvez faire :
```js
class App extends Component {
state = {
            renderForm: true,
            renderChapter: false,
            renderSection: false,
            renderNextSection: false,
            renderResume : false,
            sectionIndex: 0
}
```
Et supprimer le constructor

2019-03-18 18:23 UTC, therveux commented on react_project/src/App.js
> +        this.setState({
```js
this.setState(prevState => ({
            sectionIndex: prevState.sectionIndex + 1,
            renderSection: !prevState.renderSection,
            renderNextSection: !prevState.renderNextSection,
            renderResume : false
}))
```

2019-03-18 18:23 UTC, therveux commented on react_project/src/App.js
> +        const data = require('./Interview');
Vous pouvez initialiser la constante en dehors de la classe, son utilité est juste d'importer le fichier json

2019-03-18 18:23 UTC, therveux commented on react_project/src/App.js
> +        }
```js
const numNote = Object.keys(data.sections).reduce((acc, curr, index) => [...acc, localStorage.getItem('section' + index + 1)] ,[])
```

2019-03-18 18:23 UTC, therveux commented on react_project/src/App.js
> +        console.log('Note ' + numNote);
remove clog

2019-03-18 18:23 UTC, therveux commented on react_project/src/App.js
> +        let moy =
const

2019-03-18 18:23 UTC, therveux commented on react_project/src/App.js
> +            numNote.reduce(function(acc, val) {
`numNote.reduce((acc, val) => {`

2019-03-18 18:23 UTC, therveux commented on react_project/src/App.js
> +        if(Object.keys(data.sections).length == sectionIndex)
===

2019-03-18 18:23 UTC, therveux commented on react_project/src/App.js
> +        console.log(moy);
remove clog

2019-03-18 18:23 UTC, therveux commented on react_project/src/App.js
> +            this.state.renderResume = true;
Il faut utiliser `this.setState({ renderResume: true })`
Le state ne doit pas être muté, de cette manière le render ne sera pas trigger.

2019-03-18 18:23 UTC, Hurobaki commented on react_project/src/App.js
> +                    <div className="Form">{renderForm ? <NameForm unmountForm={this.handleFormUnmount} /> : null}</div>
Pas besoin de ternaire s'il n'y a pas de deuxième condition ...

```
{renderForm && <NameForm unmountForm={this.handleFormUnmount} /> }
```

2019-03-18 18:23 UTC, Hurobaki commented on react_project/src/App.js
> +                        {renderChapter ? (
ditto

2019-03-18 18:23 UTC, Hurobaki commented on react_project/src/App.js
> +                        {renderSection && sectionIndex < Object.keys(data.sections).length
again

2019-03-18 18:23 UTC, Hurobaki commented on react_project/src/App.js
> +                    {this.state.renderResume ? (
Destructurer renderResume + ternaire inutile

2019-03-18 18:23 UTC, Hurobaki commented on react_project/src/App.js
> +
Il y a plusieurs fois la même comparaison =>
 `sectionIndex < Object.keys(data.sections).length`

Avant le return vous pouvez créer une constante
```
const isSectionLeft = !!(sectionIndex < Object.keys(data.sections).length)
<div className="NextSection">
                        {renderNextSection && isSectionLeft
                            && this.createSection(data)}
                    </div>
```

2019-03-18 18:23 UTC, Hurobaki commented on react_project/src/Chapter.js
> +        this.state = { chapnum: props.chapnum, sections: props.sections };
C'est un peu bizarre d'utiliser les valeurs des props qui ne changent pas pour initialiser le state du composant qui est susceptible de changer. Surtout que vous n'utiliser ces valeurs que pour de l'affichage.

Retirer le this.state.

2019-03-18 18:23 UTC, Hurobaki commented on react_project/src/Chapter.js
> +        const { chapnum, sections } = this.state;
`const { chapnum, sections } = this.props`

2019-03-18 18:23 UTC, Hurobaki commented on react_project/src/Chapter.js
> +        for (let val of Object.values(secs)) {
`const arr = Object.values(secs).reduce((acc, curr) => [...acc, curr.title] ,[])`

2019-03-18 18:23 UTC, Hurobaki commented on react_project/src/Interview.json
> +      "body" : "Diffenrece between application context and activity context"
typo

2019-03-18 18:23 UTC, Hurobaki commented on react_project/src/NameForm.js
>      constructor(props) {
Sortir init state du constructor

2019-03-18 18:23 UTC, Hurobaki commented on react_project/src/Resume.js
> +        Résultat {this.state.chapnum} : {this.state.moyenne} / 5
Destructurer le state

2019-03-18 18:23 UTC, Hurobaki commented on react_project/src/Resume.js
> +            </form>
Problème indentation => utilisation de prettier

2019-03-18 18:23 UTC, Hurobaki commented on react_project/src/Resume.js
> +    constructor(props) {
Voir plus haut pour le state dans le constructor

2019-03-18 18:23 UTC, Hurobaki commented on react_project/src/Resume.js
> +import React from 'react';
`import React, { Component } from 'react';`

2019-03-18 18:23 UTC, Hurobaki commented on react_project/src/Resume.js
> +class Resume extends React.Component {
`class Resume extends Component `

2019-03-18 18:23 UTC, Hurobaki commented on react_project/src/Section.js
> +import React from 'react';
`import React, { Component } from 'react';`

2019-03-18 18:23 UTC, Hurobaki commented on react_project/src/Section.js
> +class Section extends React.Component {
`class Section extends Component`

2019-03-18 18:23 UTC, Hurobaki commented on react_project/src/Section.js
> +    constructor(props) {
Pareil pour le state voir plus haut

2019-03-18 18:23 UTC, Hurobaki commented on react_project/src/Section.js
> +        const num_section = this.state.sectionIndex + 1;
Destructurer le state

2019-03-18 18:23 UTC, Hurobaki commented on react_project/src/Section.js
> +        const sectionId = "section"+num_section.toString();
Inutile, num_section à l'air d'être un Int. Le toString() ne change rien

2019-03-18 18:23 UTC, Hurobaki commented on react_project/src/Section.js
> +        //console.log("sectionId: " + typeof sectionId);
remove comments

2019-03-18 18:23 UTC, Hurobaki commented on react_project/src/Section.js
> +
Remove spaces => prettier

2019-03-18 18:23 UTC, Hurobaki commented on react_project/src/Section.js
> +        const { title, data } = this.state;
`const { title, data } = this.props;`

2019-03-18 22:58 UTC, therveux requested changes

2019-03-18 22:58 UTC, therveux commented on react_project/src/App.js
> +                                unmountChapter={this.handleChapterUnmount}
`unmountChapter={this.handleUnmountChapter}` ?

2019-03-18 22:58 UTC, Hurobaki commented on react_project/src/Section.js
> +                <div onClick={this.handleChange} id="aBtnGroup" className="btn-group">
Pour l'affichage de la barre de vote, vous pouvez créer un Functional Component.
``` js
// GradeDisplay.js
import React from 'react';

const GRADE_NUMBER = 5;

export const GradeDisplay = ({ handleChange }) => (
    <div onClick={handleChange} id="aBtnGroup" className="btn-group">
        {[...Array(GRADE_NUMBER)].map((item, index) => (
            <button key={index} type="button" value={++index} className="btn btn-default">
                {index}
            </button>
        ))}
    </div>
);

//Section.js
import { GradeDisplay } from '../GradeDisplay';
render() {
  return (
    <div>
      ...
      <GradeDisplay handleChange={this.handleChange} />
    </div>
  )
}
```

2019-03-18 22:58 UTC, Hurobaki commented on react_project/src/NameForm.js
> +        const { value } = this.state;
Value ? Ça veut rien dire, remplacer par "userName / login" ou n'importe quoi de plus parlant :)

2019-03-18 22:58 UTC, Hurobaki commented on react_project/src/NameForm.js
> +        this.state = { value: 'Enter a Name', renderChapter: true };
Ça ne sert à rien d'initialiser value à "Enter a Name", autant utiliser le placeholder de l'input.

2019-03-18 22:58 UTC, Hurobaki commented on react_project/src/NameForm.js
> +                        <input type="text" color={'yellow'} value={value} onChange={this.handleChange} />
```html
<input type="text" placeholder="Enter a name" color={'yellow'} value={value} onChange={this.handleChange} />
```

2019-03-18 22:58 UTC, Hurobaki commented on react_project/src/NameForm.js
>  }
Remplacer la variable "value" du state par une variable plus compréhensible.

2019-03-18 22:58 UTC, Hurobaki commented on react_project/src/Resume.js
> +        console.log("clicker");
remove clog

2019-03-19 08:55 UTC, jeremybviseo commented on .idea/vcs.xml
> +<?xml version="1.0" encoding="UTF-8"?>
+ Supprimer le contenu du commit

2019-03-19 08:56 UTC, jeremybviseo commented on react_project/src/App.css
> +  animation: App-logo-spin infinite 0s linear;
animation-duration de 0s ?? il n'y a donc pas d'animation ?

2019-03-19 08:59 UTC, jeremybviseo commented on react_project/src/App.js
> +        this.setState({
Ou en destructurant : 

```
this.setState({ sectionIndex, renderSection, renderNextSection } => ({
            sectionIndex:sectionIndex + 1,
            renderSection: !renderSection,
            renderNextSection: !renderNextSection,
            renderResume : false
}))
```

2019-03-19 09:03 UTC, jeremybviseo commented on react_project/src/App.js
> +                    title={Object.values(data.sections)[sectionIndex].title}
titre est issue de data et sectionIndex,  il n'est donc pas utile de le passer en props, le composant Section est capable de l'extraire directement

2019-03-19 09:04 UTC, jeremybviseo commented on react_project/src/App.js
> +        const data = require('./Interview');
En plus le require est exécuté a chaque render => penalise les perfs

2019-03-19 09:19 UTC, jeremybviseo commented on react_project/src/App.js
> +            }, 0) / numNote.length;
Vous etes certains que numNote.length ne peux pas valoir 0 ?

2019-03-19 09:20 UTC, jeremybviseo commented on react_project/src/App.js
> +        if(Object.keys(data.sections).length == sectionIndex)
nb_section contient deja "Object.keys(data.sections).length"

2019-03-19 09:23 UTC, jeremybviseo commented on react_project/src/Chapter.js
> +        let arr = new Array();
const

2019-03-19 09:24 UTC, jeremybviseo commented on react_project/src/Chapter.js
> +                {arr.map((value, index) => (
arr est inutile ici ....
vous pouvez directement mapper sur Object.values(secs) sans utiliser de tableau intermédiaire

2019-03-19 09:28 UTC, jeremybviseo commented on react_project/src/Section.css
> +.Padding{
les classes css sont a écrire en misuscule

2019-03-19 09:29 UTC, jeremybviseo commented on react_project/src/Section.css
> +.Gris{
idem, de plus "gris" ne veux absolument rien dire "section-grey" serait peut etre mieux ?

2019-03-19 09:30 UTC, jeremybviseo commented on react_project/src/Section.css
> +.None{
idem, "none" n'est pas jun nom explicite

2019-03-19 09:46 UTC, jeremybviseo commented on react_project/src/Section.css
> +    margin-left: 37%;
les marges en % sont rarement une solution en css,  quel était le besoin ?

2019-03-20 08:44 UTC, merged